#!/usr/bin/env python3
"""Scale test: push synthetic models of growing size through the whole offline round trip, and
optionally through a real database to prove the multi-chunk sidecar survives it.

    python3 tests/scale/run_scale_test.py                      # offline tiers, no credentials
    python3 tests/scale/run_scale_test.py --profile <cz-cli>   # also the live sidecar tier

Offline, for every tier: generate -> validate -> import -> dump -> export -> validate -> diff. The
diff must be EQUIVALENT (ignoring `source`, which --source-map rewrites by design) and every step
must finish inside a budget, so a pathological slowdown fails the run instead of hanging CI.

The live phase exists because the sidecar is chunked into 2000-character properties and nothing
had ever pushed more than three chunks through a real `ALTER SEMANTIC VIEW ... SET PROPERTIES`.
The `sidecar` tier is shaped to produce seven chunks from only twelve tables.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
import time
from pathlib import Path

HERE = Path(__file__).resolve().parent
SCRIPTS = HERE.parent.parent / "scripts"
GEN = HERE / "gen_model.py"
PY = sys.executable

STEP_BUDGET_S = 30.0  # generous ceiling per step; the point is to catch blow-ups, not to benchmark

# label, datasets, fields, metrics, multitable
TIERS = [
    ("tiny", 5, 6, 5, 0),
    ("medium", 20, 10, 20, 0),
    ("large", 100, 12, 50, 0),
    ("wide", 60, 12, 40, 20),
    ("sidecar", 12, 100, 100, 0),
]

SCHEMA = "ossie_scale_test"


class Scale:
    def __init__(self) -> None:
        self.passed = 0
        self.failed = 0

    def ok(self, label: str, detail: str = "") -> None:
        print(f"PASS  {label}" + (f" ({detail})" if detail else ""))
        self.passed += 1

    def bad(self, label: str, detail: str = "") -> None:
        print(f"FAIL  {label}" + (f": {detail}" if detail else ""))
        self.failed += 1


def step(t: Scale, label: str, cmd: list[str], log: Path) -> float:
    """Run one pipeline step; return its wall time. Records a failure on non-zero exit or overrun."""
    start = time.perf_counter()
    p = subprocess.run([str(c) for c in cmd], capture_output=True, text=True)
    elapsed = time.perf_counter() - start
    log.write_text(p.stdout + p.stderr, encoding="utf-8")
    if p.returncode != 0:
        t.bad(label, f"exit {p.returncode} - {((p.stderr or p.stdout).strip().splitlines() or [''])[0][:120]}")
    elif elapsed > STEP_BUDGET_S:
        t.bad(label, f"took {elapsed:.1f}s, over the {STEP_BUDGET_S:.0f}s budget")
    else:
        t.ok(label, f"{elapsed:.2f}s")
    return elapsed


def build_dump(ddl: Path, dump: Path) -> None:
    """Mimic what sv_dump.py hands to sv_to_ossie.py, without a database."""
    create, _, alter = ddl.read_text(encoding="utf-8").partition("ALTER SEMANTIC VIEW")
    dump.write_text(json.dumps({"view": "t.sv", "ddl": create, "raw": {"desc_extended": alter}}),
                    encoding="utf-8")


def column_types(yaml_path: Path) -> dict[str, dict[str, str]]:
    """Physical column types per dataset, derived from the generator's naming contract.

    gen_model.py names numeric facts `<ds>_amount_N` (DECIMAL), day timestamps `ts_N` (DATE) and
    everything else STRING. The live phase needs real tables, so this is what it creates.
    """
    import yaml

    doc = yaml.safe_load(yaml_path.read_text(encoding="utf-8"))
    model = doc["semantic_model"][0]
    out: dict[str, dict[str, str]] = {}
    for ds in model["datasets"]:
        cols: dict[str, str] = {}
        for f in ds.get("fields", []):
            for expr in (f["expression"].get("dialects") or []):
                for col in re.findall(rf"{re.escape(ds['name'])}\.([A-Za-z_][A-Za-z0-9_]*)",
                                      expr.get("expression", "")):
                    cols[col] = ("DECIMAL(12,2)" if re.fullmatch(r"amount_\d+", col)
                                 else "DATE" if re.fullmatch(r"ts_\d+", col)
                                 else "STRING")
        out[ds["source"].split(".")[-1]] = cols
    return out


def cz(profile: str, sql: str, *, write: bool = False) -> subprocess.CompletedProcess:
    cmd = ["cz-cli", "-p", profile, "sql", "--no-limit", "--no-truncate", "-e", sql]
    if write:
        cmd.insert(4, "--write")
    return subprocess.run(cmd, capture_output=True, text=True)


def cz_file(profile: str, path: Path) -> tuple[bool, str]:
    """Run a multi-statement SQL file the way the other live suites do.

    Generated DDL starts with a `-- Generated by ...` comment; passing that through `-e` makes
    cz-cli's argument parser treat the comment as arguments (USAGE_ERROR). `-f` avoids it.
    `--batch` exits 0 even when a statement fails, so the output has to be inspected.
    """
    p = subprocess.run(["cz-cli", "-p", profile, "sql", "--write", "--batch", "-f", str(path)],
                       capture_output=True, text=True)
    if p.returncode != 0:
        return False, ((p.stderr or p.stdout).strip().splitlines() or [""])[0][:200]
    if '"error":{' in p.stdout:
        detail = re.search(r'"message":"([^"]{0,200})', p.stdout)
        return False, detail.group(1) if detail else "statement failed"
    return True, ""


def acquire_lock(profile: str) -> Path | None:
    """Same lock the bash live suites take (tests/lib/lock.sh), so all four serialise together."""
    locks = HERE.parent / ".locks"
    locks.mkdir(exist_ok=True)
    path = locks / f"{profile.replace('/', '_')}.lock"
    try:
        path.mkdir()                                    # atomic; the mkdir *is* the lock
    except FileExistsError:
        print(f"ABORT: another live suite is already running against profile '{profile}'.")
        print("       Two at once contend for the same vcluster and both start failing with")
        print(f"       JOB_TIMEOUT. Wait for it, or remove the stale lock: {path}")
        owner = path / "owner"
        if owner.exists():
            print(f"       lock held by: {owner.read_text(encoding='utf-8').strip()}")
        return None
    (path / "owner").write_text(f"pid {os.getpid()} (scale test)\n", encoding="utf-8")
    return path


def release_lock(path: Path | None) -> None:
    if path is not None:
        shutil.rmtree(path, ignore_errors=True)


def live_sidecar(t: Scale, profile: str, work: Path) -> None:
    """Push the sidecar tier through a real ALTER/DESC round trip and prove nothing is lost."""
    label = "live"
    # generate and import against the real schema rather than rewriting the offline DDL
    model = work / "sidecar.live.yaml"
    ddl = work / "sidecar.live.sql"
    gen = subprocess.run([PY, GEN, "--datasets", "12", "--fields", "100", "--metrics", "100",
                          "--multitable", "0", "-o", str(model)], capture_output=True, text=True)
    imp = subprocess.run([PY, SCRIPTS / "ossie_to_sv.py", model, "--view", f"{SCHEMA}.sv",
                          "--source-map", f"SCALE_DB.PUBLIC={SCHEMA}", "-o", str(ddl)],
                         capture_output=True, text=True)
    if gen.returncode != 0 or imp.returncode != 0:
        t.bad(f"{label}: prepare DDL", (imp.stderr or imp.stdout or gen.stderr)[:160])
        return
    lock = acquire_lock(profile)
    if lock is None:
        t.bad(f"{label}: profile lock", "another live suite holds it - see the message above")
        return
    if cz(profile, f"CREATE SCHEMA {SCHEMA}", write=True).returncode != 0:
        release_lock(lock)
        t.bad(f"{label}: create schema", f"{SCHEMA} may already exist - not touching it")
        return
    try:
        types = column_types(model)
        for table, cols in types.items():
            body = ", ".join(f"{c} {ty}" for c, ty in cols.items())
            r = cz(profile, f"CREATE OR REPLACE TABLE {SCHEMA}.{table} ({body})", write=True)
            if r.returncode != 0:
                t.bad(f"{label}: create table {table}", r.stdout[:120])
                return
        t.ok(f"{label}: created {len(types)} tables")

        sql = ddl.read_text(encoding="utf-8")
        chunks = len(set(re.findall(r"ossie_sidecar_\d+", sql)))
        ok, detail = cz_file(profile, ddl)
        if not ok:
            t.bad(f"{label}: create view with {chunks} sidecar chunks", detail)
            return
        t.ok(f"{label}: view created carrying {chunks} sidecar chunks")

        dump = work / "sidecar.dump.json"
        r = subprocess.run([PY, str(SCRIPTS / "sv_dump.py"), "--profile", profile,
                            "--view", f"{SCHEMA}.sv", "-o", str(dump)],
                           capture_output=True, text=True)
        if r.returncode != 0:
            t.bad(f"{label}: sv_dump", (r.stderr or r.stdout)[:160])
            return
        back = work / "sidecar.back.yaml"
        r = subprocess.run([PY, str(SCRIPTS / "sv_to_ossie.py"), str(dump), "-o", str(back),
                            "--issues", str(work / "sidecar.issues.json")],
                           capture_output=True, text=True)
        if r.returncode != 0:
            t.bad(f"{label}: re-export", (r.stderr or r.stdout)[:160])
            return
        issues = json.loads((work / "sidecar.issues.json").read_text(encoding="utf-8"))
        if not any("sidecar" in i["message"].lower() for i in issues):
            t.bad(f"{label}: the sidecar did not come back", "no 'sidecar found' issue")
            return
        r = subprocess.run([PY, str(SCRIPTS / "ossie_diff.py"), str(model), str(back),
                            "--ignore", "source"], capture_output=True, text=True)
        if r.returncode != 0:
            t.bad(f"{label}: round trip lost something", r.stdout[:200])
            return
        t.ok(f"{label}: {chunks}-chunk sidecar survived a real ALTER + DESC round trip")
    finally:
        cz(profile, f"DROP SEMANTIC VIEW IF EXISTS {SCHEMA}.sv", write=True)
        for table in column_types(model):
            cz(profile, f"DROP TABLE IF EXISTS {SCHEMA}.{table}", write=True)
        r = cz(profile, f"DROP SCHEMA IF EXISTS {SCHEMA}", write=True)
        t.ok(f"{label}: cleanup", "schema dropped" if r.returncode == 0 else "DROP SCHEMA failed")
        release_lock(lock)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--profile", help="cz-cli profile; enables the live sidecar phase")
    ap.add_argument("--only", help="run one tier by label")
    a = ap.parse_args()
    t = Scale()

    with tempfile.TemporaryDirectory() as tmp:
        work = Path(tmp)
        print(f"{'tier':9} {'datasets':>8} {'fields':>7} {'metrics':>8} {'chunks':>7} "
              f"{'gen':>7} {'valid':>7} {'import':>7} {'export':>7} {'diff':>7}")
        for label, ds, fl, mt, mtb in TIERS:
            if a.only and a.only != label:
                continue
            model = work / f"{label}.yaml"
            ddl = work / f"{label}.sql"
            dump = work / f"{label}.dump.json"
            back = work / f"{label}.back.yaml"
            log = work / f"{label}.log"

            gen = step(t, f"{label}: generate", [PY, GEN, "--datasets", ds, "--fields", fl,
                                                 "--metrics", mt, "--multitable", mtb, "-o", model], log)
            # gen_model.py prints its counts as JSON; read them back rather than generating twice
            counts = json.loads(log.read_text(encoding="utf-8").strip().splitlines()[-1])
            val = step(t, f"{label}: source validates",
                       [PY, SCRIPTS / "validate_ossie.py", model], log)
            imp = step(t, f"{label}: import", [PY, SCRIPTS / "ossie_to_sv.py", model,
                                               "--view", "t.sv",
                                               "--source-map", "SCALE_DB.PUBLIC=t", "-o", ddl], log)
            build_dump(ddl, dump)
            exp = step(t, f"{label}: export", [PY, SCRIPTS / "sv_to_ossie.py", dump, "-o", back], log)
            step(t, f"{label}: export validates", [PY, SCRIPTS / "validate_ossie.py", back], log)
            dif = step(t, f"{label}: round trip", [PY, SCRIPTS / "ossie_diff.py", model, back,
                                                   "--ignore", "source"], log)
            chunks = len(set(re.findall(r"ossie_sidecar_\d+", ddl.read_text(encoding="utf-8"))))
            print(f"{label:9} {counts['datasets']:>8} {counts['fields']:>7} {counts['metrics']:>8} "
                  f"{chunks:>7} {gen:>6.2f}s {val:>6.2f}s {imp:>6.2f}s {exp:>6.2f}s {dif:>6.2f}s")

        if a.profile:
            live_sidecar(t, a.profile, work)

    print(f"\nscale test: {t.passed} passed, {t.failed} failed")
    sys.exit(1 if t.failed else 0)


if __name__ == "__main__":
    main()
